// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAboutUsContentFields {
  /** heading */
  heading: string;

  /** description */
  description: string;
}

export interface IAboutUsContent extends Entry<IAboutUsContentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "aboutUsContent";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IBlogPostFields {
  /** slug */
  slug: string;

  /** title */
  title: string;

  /** description */
  description: string;

  /** coverImage */
  coverImage: Asset;

  /** body */
  body: Document;

  /** comments */
  comments?: IComment[] | undefined;
}

export interface IBlogPost extends Entry<IBlogPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blogPost";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICommentFields {
  /** commentatorName */
  commentatorName: string;

  /** content */
  content: string;

  /** parent */
  parent?: IComment | undefined;
}

/** Post comment */

export interface IComment extends Entry<ICommentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "comment";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHomeContentFields {
  /** name */
  name: string;

  /** title */
  title: string;

  /** description */
  description?: string | undefined;
}

export interface IHomeContent extends Entry<IHomeContentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "homeContent";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IIntroduceContentFields {
  /** name */
  name: string;

  /** title */
  title: string;

  /** description */
  description?: string | undefined;
}

export interface IIntroduceContent extends Entry<IIntroduceContentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "introduceContent";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITeamProfileFields {
  /** name */
  name: string;

  /** description */
  description: string;

  /** Image Url */
  imageUrl: string;
}

export interface ITeamProfile extends Entry<ITeamProfileFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "teamProfile";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "aboutUsContent"
  | "blogPost"
  | "comment"
  | "homeContent"
  | "introduceContent"
  | "teamProfile";

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
